export interface GalleryImage {
  id: string;
  title: string;
  description: string;
  imageUrl: string;
  width: number;
  height: number;
  creatorName: string;
  creatorAvatar: string;
  tags: string[];
  likes: number;
  comments: number;
  createdAt: string;
  aspectRatio: "tall" | "wide" | "square";
}

export const galleryImages: GalleryImage[] = [
  {
    id: "g-1",
    title: "Sunset Over Mountains",
    description: "A breathtaking golden hour view over misty mountain peaks, with warm orange and pink hues blending into the sky.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Budi Santoso",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Budi",
    tags: ["landscape", "sunset", "mountains", "nature"],
    likes: 342,
    comments: 18,
    createdAt: "2025-06-10",
    aspectRatio: "tall",
  },
  {
    id: "g-2",
    title: "Urban Street Art",
    description: "Vibrant mural painted on city walls, showcasing the creativity of local street artists.",
    imageUrl: "https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Siti Rahayu",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Siti",
    tags: ["art", "urban", "mural", "creativity"],
    likes: 214,
    comments: 31,
    createdAt: "2025-06-12",
    aspectRatio: "wide",
  },
  {
    id: "g-3",
    title: "Minimal Workspace",
    description: "A clean and organized desk setup with plants and natural light for maximum productivity.",
    imageUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Andi Wijaya",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Andi",
    tags: ["workspace", "minimal", "productivity", "design"],
    likes: 589,
    comments: 47,
    createdAt: "2025-06-14",
    aspectRatio: "square",
  },
  {
    id: "g-4",
    title: "Ocean Waves at Dusk",
    description: "Long exposure shot capturing the rhythmic dance of ocean waves against the shore during twilight.",
    imageUrl: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Dewi Lestari",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dewi",
    tags: ["ocean", "waves", "dusk", "photography"],
    likes: 421,
    comments: 22,
    createdAt: "2025-06-15",
    aspectRatio: "tall",
  },
  {
    id: "g-5",
    title: "Coffee Art Latte",
    description: "Expertly crafted latte art in a ceramic cup, showcasing a beautiful rosetta pattern.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    width: 800,
    height: 600,
    creatorName: "Reza Pratama",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Reza",
    tags: ["coffee", "latte", "art", "cafe"],
    likes: 178,
    comments: 12,
    createdAt: "2025-06-16",
    aspectRatio: "wide",
  },
  {
    id: "g-6",
    title: "Forest Trail Morning",
    description: "Misty forest trail at dawn, with sunlight filtering through tall pine trees creating a magical atmosphere.",
    imageUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Fitri Handayani",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fitri",
    tags: ["forest", "nature", "morning", "trail"],
    likes: 632,
    comments: 55,
    createdAt: "2025-06-17",
    aspectRatio: "tall",
  },
  {
    id: "g-7",
    title: "Abstract Color Splash",
    description: "Explosion of vibrant colors captured in freeze frame, creating a mesmerizing abstract pattern.",
    imageUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Ahmad Fajar",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad",
    tags: ["abstract", "color", "art", "splash"],
    likes: 299,
    comments: 28,
    createdAt: "2025-06-18",
    aspectRatio: "square",
  },
  {
    id: "g-8",
    title: "Neon City Nightlife",
    description: "Bustling city streets at night, illuminated by neon signs and the glow of passing vehicles.",
    imageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Maya Sari",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya",
    tags: ["city", "neon", "night", "urban"],
    likes: 745,
    comments: 89,
    createdAt: "2025-06-19",
    aspectRatio: "wide",
  },
  {
    id: "g-9",
    title: "Cherry Blossoms Spring",
    description: "Delicate pink cherry blossoms in full bloom against a soft blue sky, celebrating the arrival of spring.",
    imageUrl: "https://images.unsplash.com/photo-1522383225653-ed111181a951?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Nurul Aisyah",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nurul",
    tags: ["cherry-blossom", "spring", "flowers", "japan"],
    likes: 891,
    comments: 103,
    createdAt: "2025-06-20",
    aspectRatio: "tall",
  },
  {
    id: "g-10",
    title: "Minimalist Architecture",
    description: "Clean geometric lines of a modern building reflecting the sky, showcasing the beauty of minimalist design.",
    imageUrl: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Hendra Kurniawan",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hendra",
    tags: ["architecture", "minimalist", "building", "design"],
    likes: 367,
    comments: 41,
    createdAt: "2025-06-21",
    aspectRatio: "wide",
  },
  {
    id: "g-11",
    title: "Vintage Film Photography",
    description: "Grainy film photograph capturing a quiet afternoon in an old European alleyway.",
    imageUrl: "https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?w=600&q=80",
    width: 800,
    height: 1050,
    creatorName: "Linda Permata",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Linda",
    tags: ["film", "vintage", "photography", "alley"],
    likes: 203,
    comments: 17,
    createdAt: "2025-06-22",
    aspectRatio: "tall",
  },
  {
    id: "g-12",
    title: "Mountain Lake Reflection",
    description: "Perfect mirror-like reflection of snow-capped mountains in a crystal clear alpine lake.",
    imageUrl: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Agus Setiawan",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Agus",
    tags: ["mountain", "lake", "reflection", "nature"],
    likes: 512,
    comments: 63,
    createdAt: "2025-06-23",
    aspectRatio: "square",
  },
  // Add 38 more unique items to make 50 items
  {
    id: "g-13",
    title: "Cyberpunk Tokyo Alley",
    description: "Cyberpunk aesthetic in the streets of Shinjuku, glowing lights reflecting in the rain puddles.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Kenji Sato",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kenji",
    tags: ["neon", "cyberpunk", "tokyo", "street"],
    likes: 924,
    comments: 112,
    createdAt: "2025-06-24",
    aspectRatio: "tall",
  },
  {
    id: "g-14",
    title: "Desert Dunes Sandstorm",
    description: "Golden sand dunes stretching endlessly under a clear sky in Dubai desert safari.",
    imageUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Salma Al-Fahad",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Salma",
    tags: ["desert", "sand", "nature", "dunes"],
    likes: 412,
    comments: 35,
    createdAt: "2025-06-25",
    aspectRatio: "wide",
  },
  {
    id: "g-15",
    title: "Tropical Island Paradise",
    description: "Turquoise ocean water surrounding a secluded island beach in Maldives resort.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Alex Mercer",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    tags: ["tropical", "beach", "island", "maldives"],
    likes: 803,
    comments: 67,
    createdAt: "2025-06-26",
    aspectRatio: "square",
  },
  {
    id: "g-16",
    title: "Majestic Cathedral Gothic",
    description: "Intricate gothic architecture of a European cathedral interior with light streaming in.",
    imageUrl: "https://images.unsplash.com/photo-1478147427282-58a87a120781?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Pierre Dubois",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Pierre",
    tags: ["architecture", "gothic", "cathedral", "church"],
    likes: 319,
    comments: 24,
    createdAt: "2025-06-27",
    aspectRatio: "tall",
  },
  {
    id: "g-17",
    title: "Delightful Matcha Latte",
    description: "Organic hot matcha green tea latte art served in a cozy modern cafe setting.",
    imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Yuki Tanaka",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yuki",
    tags: ["matcha", "latte", "cafe", "beverage"],
    likes: 245,
    comments: 19,
    createdAt: "2025-06-28",
    aspectRatio: "wide",
  },
  {
    id: "g-18",
    title: "Autumn Maple Leaves",
    description: "Deep orange and crimson maple leaves resting on a stone pathway during Kyoto autumn.",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Keiko Sato",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Keiko",
    tags: ["autumn", "leaves", "japan", "nature"],
    likes: 673,
    comments: 48,
    createdAt: "2025-06-29",
    aspectRatio: "tall",
  },
  {
    id: "g-19",
    title: "Futuristic Office Space",
    description: "Co-working space layout with ergonomic chairs, plants, and smart lighting systems.",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Elena Rostova",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elena",
    tags: ["office", "workspace", "coworking", "interior"],
    likes: 412,
    comments: 31,
    createdAt: "2025-06-30",
    aspectRatio: "square",
  },
  {
    id: "g-20",
    title: "Majestic Golden Gate Bridge",
    description: "Famous suspension bridge in San Francisco surrounded by morning fog and bay waves.",
    imageUrl: "https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Michael Evans",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    tags: ["bridge", "fog", "city", "landmark"],
    likes: 839,
    comments: 72,
    createdAt: "2025-07-01",
    aspectRatio: "wide",
  },
  {
    id: "g-21",
    title: "Serene Lavender Fields",
    description: "Infinite purple rows of fragrant lavender blooming under the warm sun of Provence, France.",
    imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Jean-Pierre",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jean",
    tags: ["lavender", "flowers", "provence", "france"],
    likes: 912,
    comments: 98,
    createdAt: "2025-07-02",
    aspectRatio: "tall",
  },
  {
    id: "g-22",
    title: "Modern Cafe Facade",
    description: "Charming exterior design of a neighborhood specialty coffee shop with glass panels.",
    imageUrl: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Dian Pratama",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dian",
    tags: ["cafe", "facade", "coffee", "architecture"],
    likes: 312,
    comments: 29,
    createdAt: "2025-07-03",
    aspectRatio: "wide",
  },
  {
    id: "g-23",
    title: "Classic Retro Camera",
    description: "Analog rangefinder vintage film camera resting on a rustic wooden table.",
    imageUrl: "https://images.unsplash.com/photo-1495707902641-75cac588d2e9?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Rudi Hartono",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rudi",
    tags: ["vintage", "camera", "retro", "photography"],
    likes: 476,
    comments: 42,
    createdAt: "2025-07-04",
    aspectRatio: "square",
  },
  {
    id: "g-24",
    title: "Snowy Pine Forest Trail",
    description: "A trail through snow covered fir trees in Switzerland winter resort, silent and cold.",
    imageUrl: "https://images.unsplash.com/photo-1482862549707-f63cb32c5fd9?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Hans Müller",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hans",
    tags: ["snow", "forest", "winter", "switzerland"],
    likes: 721,
    comments: 61,
    createdAt: "2025-07-05",
    aspectRatio: "tall",
  },
  {
    id: "g-25",
    title: "Tasty Strawberry Pancake",
    description: "Fluffy breakfast pancakes stacked high with fresh organic strawberries and maple syrup.",
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Maria Rossi",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    tags: ["food", "pancake", "strawberry", "breakfast"],
    likes: 541,
    comments: 38,
    createdAt: "2025-07-06",
    aspectRatio: "wide",
  },
  {
    id: "g-26",
    title: "Cosmopolitan Skyline Dusk",
    description: "Stunning aerial perspective of Singapore skyline at twilight, highlighting neon skyscraper architecture.",
    imageUrl: "https://images.unsplash.com/photo-1496568818309-53d7c7753022?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Winston Tan",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Winston",
    tags: ["skyline", "city", "twilight", "singapore"],
    likes: 804,
    comments: 67,
    createdAt: "2025-07-07",
    aspectRatio: "tall",
  },
  {
    id: "g-27",
    title: "Abstract Line Art Geometry",
    description: "Monochrome vector geometry lines forming abstract futuristic pattern overlays.",
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Gita Amalia",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Gita",
    tags: ["abstract", "geometry", "monochrome", "pattern"],
    likes: 198,
    comments: 15,
    createdAt: "2025-07-08",
    aspectRatio: "square",
  },
  {
    id: "g-28",
    title: "Majestic Grand Canyon Peaks",
    description: "Windswept canyons in Arizona showcasing red sand stone formations under warm afternoon sunlight.",
    imageUrl: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Dustin Snyder",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dustin",
    tags: ["nature", "canyon", "arizona", "landscape"],
    likes: 672,
    comments: 49,
    createdAt: "2025-07-09",
    aspectRatio: "wide",
  },
  {
    id: "g-29",
    title: "Traditional Kyoto Streets",
    description: "Preserved historic street in Kyoto with wooden buildings and sunset glows.",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Hiroshi Ito",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hiroshi",
    tags: ["kyoto", "japan", "historic", "travel"],
    likes: 864,
    comments: 91,
    createdAt: "2025-07-10",
    aspectRatio: "tall",
  },
  {
    id: "g-30",
    title: "Clean Modern Desk Setup",
    description: "Workspace aesthetic with mechanical keyboard, trackpad, and desk mat in natural daylight.",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Tommy Wijaya",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tommy",
    tags: ["workspace", "productivity", "setup", "keyboard"],
    likes: 429,
    comments: 37,
    createdAt: "2025-07-11",
    aspectRatio: "wide",
  },
  {
    id: "g-31",
    title: "Enchanting Aurora Borealis",
    description: "Vibrant green northern lights twisting above snow covered trees in Tromso, Norway.",
    imageUrl: "https://images.unsplash.com/photo-1483168527879-c66136b56105?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Astrid Lind",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Astrid",
    tags: ["aurora", "norway", "night", "nature"],
    likes: 1204,
    comments: 138,
    createdAt: "2025-07-12",
    aspectRatio: "tall",
  },
  {
    id: "g-32",
    title: "Exquisite Sushi Platter",
    description: "Premium chef selected Nigiri and Maki rolls artfully arranged on a traditional slate plate.",
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Takeshi Sato",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Takeshi",
    tags: ["sushi", "food", "japan", "gourmet"],
    likes: 673,
    comments: 54,
    createdAt: "2025-07-13",
    aspectRatio: "square",
  },
  {
    id: "g-33",
    title: "Autumn River Creek",
    description: "Gentle mountain stream flowing through yellow and orange maple forests in Canada.",
    imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Liam Carter",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Liam",
    tags: ["autumn", "river", "forest", "nature"],
    likes: 803,
    comments: 62,
    createdAt: "2025-07-14",
    aspectRatio: "wide",
  },
  {
    id: "g-34",
    title: "Majestic Eiffel Tower Sunset",
    description: "Breathtaking sky silhouette of the Eiffel Tower glowing during warm summer twilight in Paris.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Chloe Dupont",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chloe",
    tags: ["eiffel", "paris", "sunset", "travel"],
    likes: 1104,
    comments: 94,
    createdAt: "2025-07-15",
    aspectRatio: "tall",
  },
  {
    id: "g-35",
    title: "Stunning Cappadocia Hot Balloons",
    description: "Dozens of colorful hot air balloons floating above stone valleys during Cappadocia sunrise.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Emre Yilmaz",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emre",
    tags: ["balloon", "cappadocia", "sunrise", "turkey"],
    likes: 981,
    comments: 87,
    createdAt: "2025-07-16",
    aspectRatio: "wide",
  },
  {
    id: "g-36",
    title: "Charming Coastal Town Cliff",
    description: "Cinque Terre cliffs overlooking turquoise Ligurian sea with pastel colored houses.",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    width: 800,
    height: 1100,
    creatorName: "Luca Moretti",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Luca",
    tags: ["coastal", "italy", "sea", "travel"],
    likes: 843,
    comments: 59,
    createdAt: "2025-07-17",
    aspectRatio: "tall",
  },
  {
    id: "g-37",
    title: "Warm Brew Pour Over",
    description: "Hand drip specialty coffee extraction process using glass server and paper filter.",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Siti Rahma",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahma",
    tags: ["coffee", "pourover", "cafe", "brewing"],
    likes: 312,
    comments: 24,
    createdAt: "2025-07-18",
    aspectRatio: "square",
  },
  {
    id: "g-38",
    title: "Minimalist Desert Oasis",
    description: "Lone palm tree next to a geometric swimming pool in Palm Springs desert modernism home.",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "James Dean",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    tags: ["pool", "palmsprings", "minimalist", "design"],
    likes: 589,
    comments: 41,
    createdAt: "2025-07-19",
    aspectRatio: "wide",
  },
  {
    id: "g-39",
    title: "Snowy Mountain Peaks Peak",
    description: "Majestic snow capped peak of Mont Blanc reflecting crisp afternoon light in Chamonix, France.",
    imageUrl: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Jean Dupont",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JeanD",
    tags: ["mountain", "snow", "alps", "nature"],
    likes: 742,
    comments: 55,
    createdAt: "2025-07-20",
    aspectRatio: "tall",
  },
  {
    id: "g-40",
    title: "Abstract Neon Glow Tube",
    description: "Close-up macro shot of colored neon gas tubes forming geometric modern abstract structures.",
    imageUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Ryan Geller",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan",
    tags: ["neon", "glow", "abstract", "color"],
    likes: 310,
    comments: 22,
    createdAt: "2025-07-21",
    aspectRatio: "square",
  },
  {
    id: "g-41",
    title: "Vibrant Tropical Rain Forest",
    description: "Lush green canopy and ferns capturing sunlight inside a rainforest in Ubud, Bali.",
    imageUrl: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "I Wayan",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wayan",
    tags: ["forest", "ubud", "bali", "nature"],
    likes: 673,
    comments: 48,
    createdAt: "2025-07-22",
    aspectRatio: "wide",
  },
  {
    id: "g-42",
    title: "Enchanting Lavender Twilight",
    description: "Lavender rows fading into blue hour twilight under star dotted skies in Valensole.",
    imageUrl: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Sophie Martin",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
    tags: ["lavender", "twilight", "france", "nature"],
    likes: 894,
    comments: 72,
    createdAt: "2025-07-23",
    aspectRatio: "tall",
  },
  {
    id: "g-43",
    title: "Delicious Pizza Margherita",
    description: "Fresh wood fired Napoletana pizza with buffalo mozzarella, basil, and San Marzano tomato sauce.",
    imageUrl: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Giovanni Rossi",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Giovanni",
    tags: ["pizza", "food", "italy", "gourmet"],
    likes: 712,
    comments: 49,
    createdAt: "2025-07-24",
    aspectRatio: "square",
  },
  {
    id: "g-44",
    title: "Autumn Walkway Pathway",
    description: "Yellow and red leaves blanketing a historic park avenue in Central Park, New York.",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "John Miller",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=JohnM",
    tags: ["autumn", "park", "nyc", "nature"],
    likes: 804,
    comments: 63,
    createdAt: "2025-07-25",
    aspectRatio: "wide",
  },
  {
    id: "g-45",
    title: "Traditional Pagoda Pagoda",
    description: "Stunning red Yasaka pagoda standing tall under pink twilight sky in Kyoto, Japan.",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Kaito Sato",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kaito",
    tags: ["pagoda", "kyoto", "japan", "travel"],
    likes: 914,
    comments: 79,
    createdAt: "2025-07-26",
    aspectRatio: "tall",
  },
  {
    id: "g-46",
    title: "Clean Mechanical Keyboard",
    description: "Minimalist layout mechanical keyboard with custom dye-sub keycaps on a desk mat.",
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
    width: 900,
    height: 600,
    creatorName: "Bagus Setiawan",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bagus",
    tags: ["keyboard", "setup", "workspace", "minimalist"],
    likes: 318,
    comments: 24,
    createdAt: "2025-07-27",
    aspectRatio: "wide",
  },
  {
    id: "g-47",
    title: "Vivid Aurora Forest",
    description: "Northern lights painting green ribbons across starry night sky above polar lake.",
    imageUrl: "https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=600&q=80",
    width: 800,
    height: 800,
    creatorName: "Sven Nyström",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sven",
    tags: ["aurora", "polar", "forest", "nature"],
    likes: 679,
    comments: 53,
    createdAt: "2025-07-28",
    aspectRatio: "square",
  },
  {
    id: "g-48",
    title: "Mountain Creek Twilight",
    description: "Flowing cold stream through alpine forests under glowing orange sunset cloud shapes.",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    width: 1200,
    height: 800,
    creatorName: "Christian Brown",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
    tags: ["river", "sunset", "mountain", "nature"],
    likes: 803,
    comments: 64,
    createdAt: "2025-07-29",
    aspectRatio: "wide",
  },
  {
    id: "g-49",
    title: "Cyberpunk Tokyo Tower",
    description: "Glowing neon cyberpunk street looking towards the iconic red Tokyo Tower at night.",
    imageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=600&q=80",
    width: 800,
    height: 1200,
    creatorName: "Takashi Ito",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Takashi",
    tags: ["neon", "cyberpunk", "tokyo", "travel"],
    likes: 1042,
    comments: 98,
    createdAt: "2025-07-30",
    aspectRatio: "tall",
  },
  {
    id: "g-50",
    title: "Exquisite Matcha Mochi",
    description: "Fresh handmade green tea mochi dessert dusting with ceremonial grade Uji matcha.",
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&q=80",
    width: 900,
    height: 900,
    creatorName: "Sakura Tanaka",
    creatorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sakura",
    tags: ["matcha", "mochi", "sweet", "japan"],
    likes: 562,
    comments: 41,
    createdAt: "2025-07-31",
    aspectRatio: "square",
  },
];
