/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardFinancingRouteImport } from './routes/_dashboard.financing'
import { Route as DashboardDocsRouteImport } from './routes/_dashboard.docs'
import { Route as DashboardCustomerServiceRouteImport } from './routes/_dashboard.customer-service'
import { Route as DashboardCrmBlastRouteImport } from './routes/_dashboard.crm-blast'
import { Route as DashboardWorkspaceCreatorRouteImport } from './routes/_dashboard.workspace.creator'
import { Route as DashboardWorkspaceBusinessRouteImport } from './routes/_dashboard.workspace.business'
import { Route as DashboardWorkspaceAccountRouteImport } from './routes/_dashboard.workspace.account'
import { Route as DashboardCustomerServiceWhatsappRouteImport } from './routes/_dashboard.customer-service.whatsapp'
import { Route as DashboardCustomerServiceWebsiteRouteImport } from './routes/_dashboard.customer-service.website'
import { Route as DashboardCustomerServiceGmailRouteImport } from './routes/_dashboard.customer-service.gmail'
import { Route as DashboardCustomerServiceAllRouteImport } from './routes/_dashboard.customer-service.all'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFinancingRoute = DashboardFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomerServiceRoute =
  DashboardCustomerServiceRouteImport.update({
    id: '/customer-service',
    path: '/customer-service',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCrmBlastRoute = DashboardCrmBlastRouteImport.update({
  id: '/crm-blast',
  path: '/crm-blast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceCreatorRoute =
  DashboardWorkspaceCreatorRouteImport.update({
    id: '/workspace/creator',
    path: '/workspace/creator',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceBusinessRoute =
  DashboardWorkspaceBusinessRouteImport.update({
    id: '/workspace/business',
    path: '/workspace/business',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceAccountRoute =
  DashboardWorkspaceAccountRouteImport.update({
    id: '/workspace/account',
    path: '/workspace/account',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCustomerServiceWhatsappRoute =
  DashboardCustomerServiceWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceWebsiteRoute =
  DashboardCustomerServiceWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceGmailRoute =
  DashboardCustomerServiceGmailRouteImport.update({
    id: '/gmail',
    path: '/gmail',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceAllRoute =
  DashboardCustomerServiceAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm-blast': typeof DashboardCrmBlastRoute
  '/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/docs': typeof DashboardDocsRoute
  '/financing': typeof DashboardFinancingRoute
  '/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/workspace/business': typeof DashboardWorkspaceBusinessRoute
  '/workspace/creator': typeof DashboardWorkspaceCreatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm-blast': typeof DashboardCrmBlastRoute
  '/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/docs': typeof DashboardDocsRoute
  '/financing': typeof DashboardFinancingRoute
  '/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/workspace/business': typeof DashboardWorkspaceBusinessRoute
  '/workspace/creator': typeof DashboardWorkspaceCreatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/crm-blast': typeof DashboardCrmBlastRoute
  '/_dashboard/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/_dashboard/docs': typeof DashboardDocsRoute
  '/_dashboard/financing': typeof DashboardFinancingRoute
  '/_dashboard/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/_dashboard/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/_dashboard/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/_dashboard/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/_dashboard/workspace/account': typeof DashboardWorkspaceAccountRoute
  '/_dashboard/workspace/business': typeof DashboardWorkspaceBusinessRoute
  '/_dashboard/workspace/creator': typeof DashboardWorkspaceCreatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm-blast'
    | '/customer-service'
    | '/docs'
    | '/financing'
    | '/customer-service/all'
    | '/customer-service/gmail'
    | '/customer-service/website'
    | '/customer-service/whatsapp'
    | '/workspace/account'
    | '/workspace/business'
    | '/workspace/creator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm-blast'
    | '/customer-service'
    | '/docs'
    | '/financing'
    | '/customer-service/all'
    | '/customer-service/gmail'
    | '/customer-service/website'
    | '/customer-service/whatsapp'
    | '/workspace/account'
    | '/workspace/business'
    | '/workspace/creator'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/crm-blast'
    | '/_dashboard/customer-service'
    | '/_dashboard/docs'
    | '/_dashboard/financing'
    | '/_dashboard/customer-service/all'
    | '/_dashboard/customer-service/gmail'
    | '/_dashboard/customer-service/website'
    | '/_dashboard/customer-service/whatsapp'
    | '/_dashboard/workspace/account'
    | '/_dashboard/workspace/business'
    | '/_dashboard/workspace/creator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/financing': {
      id: '/_dashboard/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof DashboardFinancingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs': {
      id: '/_dashboard/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customer-service': {
      id: '/_dashboard/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof DashboardCustomerServiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/crm-blast': {
      id: '/_dashboard/crm-blast'
      path: '/crm-blast'
      fullPath: '/crm-blast'
      preLoaderRoute: typeof DashboardCrmBlastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/creator': {
      id: '/_dashboard/workspace/creator'
      path: '/workspace/creator'
      fullPath: '/workspace/creator'
      preLoaderRoute: typeof DashboardWorkspaceCreatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/business': {
      id: '/_dashboard/workspace/business'
      path: '/workspace/business'
      fullPath: '/workspace/business'
      preLoaderRoute: typeof DashboardWorkspaceBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/account': {
      id: '/_dashboard/workspace/account'
      path: '/workspace/account'
      fullPath: '/workspace/account'
      preLoaderRoute: typeof DashboardWorkspaceAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customer-service/whatsapp': {
      id: '/_dashboard/customer-service/whatsapp'
      path: '/whatsapp'
      fullPath: '/customer-service/whatsapp'
      preLoaderRoute: typeof DashboardCustomerServiceWhatsappRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/website': {
      id: '/_dashboard/customer-service/website'
      path: '/website'
      fullPath: '/customer-service/website'
      preLoaderRoute: typeof DashboardCustomerServiceWebsiteRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/gmail': {
      id: '/_dashboard/customer-service/gmail'
      path: '/gmail'
      fullPath: '/customer-service/gmail'
      preLoaderRoute: typeof DashboardCustomerServiceGmailRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/all': {
      id: '/_dashboard/customer-service/all'
      path: '/all'
      fullPath: '/customer-service/all'
      preLoaderRoute: typeof DashboardCustomerServiceAllRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
  }
}

interface DashboardCustomerServiceRouteChildren {
  DashboardCustomerServiceAllRoute: typeof DashboardCustomerServiceAllRoute
  DashboardCustomerServiceGmailRoute: typeof DashboardCustomerServiceGmailRoute
  DashboardCustomerServiceWebsiteRoute: typeof DashboardCustomerServiceWebsiteRoute
  DashboardCustomerServiceWhatsappRoute: typeof DashboardCustomerServiceWhatsappRoute
}

const DashboardCustomerServiceRouteChildren: DashboardCustomerServiceRouteChildren =
  {
    DashboardCustomerServiceAllRoute: DashboardCustomerServiceAllRoute,
    DashboardCustomerServiceGmailRoute: DashboardCustomerServiceGmailRoute,
    DashboardCustomerServiceWebsiteRoute: DashboardCustomerServiceWebsiteRoute,
    DashboardCustomerServiceWhatsappRoute:
      DashboardCustomerServiceWhatsappRoute,
  }

const DashboardCustomerServiceRouteWithChildren =
  DashboardCustomerServiceRoute._addFileChildren(
    DashboardCustomerServiceRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardCrmBlastRoute: typeof DashboardCrmBlastRoute
  DashboardCustomerServiceRoute: typeof DashboardCustomerServiceRouteWithChildren
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardFinancingRoute: typeof DashboardFinancingRoute
  DashboardWorkspaceAccountRoute: typeof DashboardWorkspaceAccountRoute
  DashboardWorkspaceBusinessRoute: typeof DashboardWorkspaceBusinessRoute
  DashboardWorkspaceCreatorRoute: typeof DashboardWorkspaceCreatorRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCrmBlastRoute: DashboardCrmBlastRoute,
  DashboardCustomerServiceRoute: DashboardCustomerServiceRouteWithChildren,
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardFinancingRoute: DashboardFinancingRoute,
  DashboardWorkspaceAccountRoute: DashboardWorkspaceAccountRoute,
  DashboardWorkspaceBusinessRoute: DashboardWorkspaceBusinessRoute,
  DashboardWorkspaceCreatorRoute: DashboardWorkspaceCreatorRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
