/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardFinancingRouteImport } from './routes/_dashboard.financing'
import { Route as DashboardDocsRouteImport } from './routes/_dashboard.docs'
import { Route as DashboardCustomerServiceRouteImport } from './routes/_dashboard.customer-service'
import { Route as DashboardCrmBlastRouteImport } from './routes/_dashboard.crm-blast'
import { Route as DashboardWorkspaceRssRouteImport } from './routes/_dashboard.workspace.rss'
import { Route as DashboardWorkspacePaymentRouteImport } from './routes/_dashboard.workspace.payment'
import { Route as DashboardWorkspaceCreatorRouteImport } from './routes/_dashboard.workspace.creator'
import { Route as DashboardWorkspaceBusinessRouteImport } from './routes/_dashboard.workspace.business'
import { Route as DashboardWorkspaceAccountRouteImport } from './routes/_dashboard.workspace.account'
import { Route as DashboardDocsManagementRouteImport } from './routes/_dashboard.docs.management'
import { Route as DashboardDocsLegalityRouteImport } from './routes/_dashboard.docs.legality'
import { Route as DashboardCustomerServiceWhatsappRouteImport } from './routes/_dashboard.customer-service.whatsapp'
import { Route as DashboardCustomerServiceWebsiteRouteImport } from './routes/_dashboard.customer-service.website'
import { Route as DashboardCustomerServiceGmailRouteImport } from './routes/_dashboard.customer-service.gmail'
import { Route as DashboardCustomerServiceAllRouteImport } from './routes/_dashboard.customer-service.all'
import { Route as DashboardWorkspaceCreatorIndexRouteImport } from './routes/_dashboard.workspace.creator.index'
import { Route as DashboardWorkspaceBusinessIndexRouteImport } from './routes/_dashboard.workspace.business.index'
import { Route as DashboardWorkspaceDiscountVoucherRouteImport } from './routes/_dashboard.workspace.discount.voucher'
import { Route as DashboardWorkspaceDiscountReferralRouteImport } from './routes/_dashboard.workspace.discount.referral'
import { Route as DashboardWorkspaceCreatorGalleryRouteImport } from './routes/_dashboard.workspace.creator.gallery'
import { Route as DashboardWorkspaceBusinessTokenInjectRouteImport } from './routes/_dashboard.workspace.business.token-inject'
import { Route as DashboardWorkspaceAiModelTextRouteImport } from './routes/_dashboard.workspace.ai-model.text'
import { Route as DashboardWorkspaceAiModelImageRouteImport } from './routes/_dashboard.workspace.ai-model.image'
import { Route as DashboardWorkspaceAccountUserRouteImport } from './routes/_dashboard.workspace.account.user'
import { Route as DashboardWorkspaceAccountRoleRouteImport } from './routes/_dashboard.workspace.account.role'
import { Route as DashboardWorkspaceAccountCreatorRouteImport } from './routes/_dashboard.workspace.account.creator'
import { Route as DashboardWorkspaceAccountAdminRouteImport } from './routes/_dashboard.workspace.account.admin'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinancingRoute = DashboardFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomerServiceRoute =
  DashboardCustomerServiceRouteImport.update({
    id: '/customer-service',
    path: '/customer-service',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCrmBlastRoute = DashboardCrmBlastRouteImport.update({
  id: '/crm-blast',
  path: '/crm-blast',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspaceRssRoute = DashboardWorkspaceRssRouteImport.update({
  id: '/workspace/rss',
  path: '/workspace/rss',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspacePaymentRoute =
  DashboardWorkspacePaymentRouteImport.update({
    id: '/workspace/payment',
    path: '/workspace/payment',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceCreatorRoute =
  DashboardWorkspaceCreatorRouteImport.update({
    id: '/workspace/creator',
    path: '/workspace/creator',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceBusinessRoute =
  DashboardWorkspaceBusinessRouteImport.update({
    id: '/workspace/business',
    path: '/workspace/business',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceAccountRoute =
  DashboardWorkspaceAccountRouteImport.update({
    id: '/workspace/account',
    path: '/workspace/account',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsManagementRoute = DashboardDocsManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => DashboardDocsRoute,
} as any)
const DashboardDocsLegalityRoute = DashboardDocsLegalityRouteImport.update({
  id: '/legality',
  path: '/legality',
  getParentRoute: () => DashboardDocsRoute,
} as any)
const DashboardCustomerServiceWhatsappRoute =
  DashboardCustomerServiceWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceWebsiteRoute =
  DashboardCustomerServiceWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceGmailRoute =
  DashboardCustomerServiceGmailRouteImport.update({
    id: '/gmail',
    path: '/gmail',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardCustomerServiceAllRoute =
  DashboardCustomerServiceAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => DashboardCustomerServiceRoute,
  } as any)
const DashboardWorkspaceCreatorIndexRoute =
  DashboardWorkspaceCreatorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceCreatorRoute,
  } as any)
const DashboardWorkspaceBusinessIndexRoute =
  DashboardWorkspaceBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceBusinessRoute,
  } as any)
const DashboardWorkspaceDiscountVoucherRoute =
  DashboardWorkspaceDiscountVoucherRouteImport.update({
    id: '/workspace/discount/voucher',
    path: '/workspace/discount/voucher',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceDiscountReferralRoute =
  DashboardWorkspaceDiscountReferralRouteImport.update({
    id: '/workspace/discount/referral',
    path: '/workspace/discount/referral',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceCreatorGalleryRoute =
  DashboardWorkspaceCreatorGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => DashboardWorkspaceCreatorRoute,
  } as any)
const DashboardWorkspaceBusinessTokenInjectRoute =
  DashboardWorkspaceBusinessTokenInjectRouteImport.update({
    id: '/token-inject',
    path: '/token-inject',
    getParentRoute: () => DashboardWorkspaceBusinessRoute,
  } as any)
const DashboardWorkspaceAiModelTextRoute =
  DashboardWorkspaceAiModelTextRouteImport.update({
    id: '/workspace/ai-model/text',
    path: '/workspace/ai-model/text',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceAiModelImageRoute =
  DashboardWorkspaceAiModelImageRouteImport.update({
    id: '/workspace/ai-model/image',
    path: '/workspace/ai-model/image',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkspaceAccountUserRoute =
  DashboardWorkspaceAccountUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => DashboardWorkspaceAccountRoute,
  } as any)
const DashboardWorkspaceAccountRoleRoute =
  DashboardWorkspaceAccountRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => DashboardWorkspaceAccountRoute,
  } as any)
const DashboardWorkspaceAccountCreatorRoute =
  DashboardWorkspaceAccountCreatorRouteImport.update({
    id: '/creator',
    path: '/creator',
    getParentRoute: () => DashboardWorkspaceAccountRoute,
  } as any)
const DashboardWorkspaceAccountAdminRoute =
  DashboardWorkspaceAccountAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => DashboardWorkspaceAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm-blast': typeof DashboardCrmBlastRoute
  '/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/docs': typeof DashboardDocsRouteWithChildren
  '/financing': typeof DashboardFinancingRoute
  '/settings': typeof DashboardSettingsRoute
  '/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/docs/legality': typeof DashboardDocsLegalityRoute
  '/docs/management': typeof DashboardDocsManagementRoute
  '/workspace/account': typeof DashboardWorkspaceAccountRouteWithChildren
  '/workspace/business': typeof DashboardWorkspaceBusinessRouteWithChildren
  '/workspace/creator': typeof DashboardWorkspaceCreatorRouteWithChildren
  '/workspace/payment': typeof DashboardWorkspacePaymentRoute
  '/workspace/rss': typeof DashboardWorkspaceRssRoute
  '/workspace/account/admin': typeof DashboardWorkspaceAccountAdminRoute
  '/workspace/account/creator': typeof DashboardWorkspaceAccountCreatorRoute
  '/workspace/account/role': typeof DashboardWorkspaceAccountRoleRoute
  '/workspace/account/user': typeof DashboardWorkspaceAccountUserRoute
  '/workspace/ai-model/image': typeof DashboardWorkspaceAiModelImageRoute
  '/workspace/ai-model/text': typeof DashboardWorkspaceAiModelTextRoute
  '/workspace/business/token-inject': typeof DashboardWorkspaceBusinessTokenInjectRoute
  '/workspace/creator/gallery': typeof DashboardWorkspaceCreatorGalleryRoute
  '/workspace/discount/referral': typeof DashboardWorkspaceDiscountReferralRoute
  '/workspace/discount/voucher': typeof DashboardWorkspaceDiscountVoucherRoute
  '/workspace/business/': typeof DashboardWorkspaceBusinessIndexRoute
  '/workspace/creator/': typeof DashboardWorkspaceCreatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm-blast': typeof DashboardCrmBlastRoute
  '/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/docs': typeof DashboardDocsRouteWithChildren
  '/financing': typeof DashboardFinancingRoute
  '/settings': typeof DashboardSettingsRoute
  '/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/docs/legality': typeof DashboardDocsLegalityRoute
  '/docs/management': typeof DashboardDocsManagementRoute
  '/workspace/account': typeof DashboardWorkspaceAccountRouteWithChildren
  '/workspace/payment': typeof DashboardWorkspacePaymentRoute
  '/workspace/rss': typeof DashboardWorkspaceRssRoute
  '/workspace/account/admin': typeof DashboardWorkspaceAccountAdminRoute
  '/workspace/account/creator': typeof DashboardWorkspaceAccountCreatorRoute
  '/workspace/account/role': typeof DashboardWorkspaceAccountRoleRoute
  '/workspace/account/user': typeof DashboardWorkspaceAccountUserRoute
  '/workspace/ai-model/image': typeof DashboardWorkspaceAiModelImageRoute
  '/workspace/ai-model/text': typeof DashboardWorkspaceAiModelTextRoute
  '/workspace/business/token-inject': typeof DashboardWorkspaceBusinessTokenInjectRoute
  '/workspace/creator/gallery': typeof DashboardWorkspaceCreatorGalleryRoute
  '/workspace/discount/referral': typeof DashboardWorkspaceDiscountReferralRoute
  '/workspace/discount/voucher': typeof DashboardWorkspaceDiscountVoucherRoute
  '/workspace/business': typeof DashboardWorkspaceBusinessIndexRoute
  '/workspace/creator': typeof DashboardWorkspaceCreatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/crm-blast': typeof DashboardCrmBlastRoute
  '/_dashboard/customer-service': typeof DashboardCustomerServiceRouteWithChildren
  '/_dashboard/docs': typeof DashboardDocsRouteWithChildren
  '/_dashboard/financing': typeof DashboardFinancingRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/customer-service/all': typeof DashboardCustomerServiceAllRoute
  '/_dashboard/customer-service/gmail': typeof DashboardCustomerServiceGmailRoute
  '/_dashboard/customer-service/website': typeof DashboardCustomerServiceWebsiteRoute
  '/_dashboard/customer-service/whatsapp': typeof DashboardCustomerServiceWhatsappRoute
  '/_dashboard/docs/legality': typeof DashboardDocsLegalityRoute
  '/_dashboard/docs/management': typeof DashboardDocsManagementRoute
  '/_dashboard/workspace/account': typeof DashboardWorkspaceAccountRouteWithChildren
  '/_dashboard/workspace/business': typeof DashboardWorkspaceBusinessRouteWithChildren
  '/_dashboard/workspace/creator': typeof DashboardWorkspaceCreatorRouteWithChildren
  '/_dashboard/workspace/payment': typeof DashboardWorkspacePaymentRoute
  '/_dashboard/workspace/rss': typeof DashboardWorkspaceRssRoute
  '/_dashboard/workspace/account/admin': typeof DashboardWorkspaceAccountAdminRoute
  '/_dashboard/workspace/account/creator': typeof DashboardWorkspaceAccountCreatorRoute
  '/_dashboard/workspace/account/role': typeof DashboardWorkspaceAccountRoleRoute
  '/_dashboard/workspace/account/user': typeof DashboardWorkspaceAccountUserRoute
  '/_dashboard/workspace/ai-model/image': typeof DashboardWorkspaceAiModelImageRoute
  '/_dashboard/workspace/ai-model/text': typeof DashboardWorkspaceAiModelTextRoute
  '/_dashboard/workspace/business/token-inject': typeof DashboardWorkspaceBusinessTokenInjectRoute
  '/_dashboard/workspace/creator/gallery': typeof DashboardWorkspaceCreatorGalleryRoute
  '/_dashboard/workspace/discount/referral': typeof DashboardWorkspaceDiscountReferralRoute
  '/_dashboard/workspace/discount/voucher': typeof DashboardWorkspaceDiscountVoucherRoute
  '/_dashboard/workspace/business/': typeof DashboardWorkspaceBusinessIndexRoute
  '/_dashboard/workspace/creator/': typeof DashboardWorkspaceCreatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm-blast'
    | '/customer-service'
    | '/docs'
    | '/financing'
    | '/settings'
    | '/customer-service/all'
    | '/customer-service/gmail'
    | '/customer-service/website'
    | '/customer-service/whatsapp'
    | '/docs/legality'
    | '/docs/management'
    | '/workspace/account'
    | '/workspace/business'
    | '/workspace/creator'
    | '/workspace/payment'
    | '/workspace/rss'
    | '/workspace/account/admin'
    | '/workspace/account/creator'
    | '/workspace/account/role'
    | '/workspace/account/user'
    | '/workspace/ai-model/image'
    | '/workspace/ai-model/text'
    | '/workspace/business/token-inject'
    | '/workspace/creator/gallery'
    | '/workspace/discount/referral'
    | '/workspace/discount/voucher'
    | '/workspace/business/'
    | '/workspace/creator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm-blast'
    | '/customer-service'
    | '/docs'
    | '/financing'
    | '/settings'
    | '/customer-service/all'
    | '/customer-service/gmail'
    | '/customer-service/website'
    | '/customer-service/whatsapp'
    | '/docs/legality'
    | '/docs/management'
    | '/workspace/account'
    | '/workspace/payment'
    | '/workspace/rss'
    | '/workspace/account/admin'
    | '/workspace/account/creator'
    | '/workspace/account/role'
    | '/workspace/account/user'
    | '/workspace/ai-model/image'
    | '/workspace/ai-model/text'
    | '/workspace/business/token-inject'
    | '/workspace/creator/gallery'
    | '/workspace/discount/referral'
    | '/workspace/discount/voucher'
    | '/workspace/business'
    | '/workspace/creator'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/crm-blast'
    | '/_dashboard/customer-service'
    | '/_dashboard/docs'
    | '/_dashboard/financing'
    | '/_dashboard/settings'
    | '/_dashboard/customer-service/all'
    | '/_dashboard/customer-service/gmail'
    | '/_dashboard/customer-service/website'
    | '/_dashboard/customer-service/whatsapp'
    | '/_dashboard/docs/legality'
    | '/_dashboard/docs/management'
    | '/_dashboard/workspace/account'
    | '/_dashboard/workspace/business'
    | '/_dashboard/workspace/creator'
    | '/_dashboard/workspace/payment'
    | '/_dashboard/workspace/rss'
    | '/_dashboard/workspace/account/admin'
    | '/_dashboard/workspace/account/creator'
    | '/_dashboard/workspace/account/role'
    | '/_dashboard/workspace/account/user'
    | '/_dashboard/workspace/ai-model/image'
    | '/_dashboard/workspace/ai-model/text'
    | '/_dashboard/workspace/business/token-inject'
    | '/_dashboard/workspace/creator/gallery'
    | '/_dashboard/workspace/discount/referral'
    | '/_dashboard/workspace/discount/voucher'
    | '/_dashboard/workspace/business/'
    | '/_dashboard/workspace/creator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/financing': {
      id: '/_dashboard/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof DashboardFinancingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs': {
      id: '/_dashboard/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customer-service': {
      id: '/_dashboard/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof DashboardCustomerServiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/crm-blast': {
      id: '/_dashboard/crm-blast'
      path: '/crm-blast'
      fullPath: '/crm-blast'
      preLoaderRoute: typeof DashboardCrmBlastRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/rss': {
      id: '/_dashboard/workspace/rss'
      path: '/workspace/rss'
      fullPath: '/workspace/rss'
      preLoaderRoute: typeof DashboardWorkspaceRssRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/payment': {
      id: '/_dashboard/workspace/payment'
      path: '/workspace/payment'
      fullPath: '/workspace/payment'
      preLoaderRoute: typeof DashboardWorkspacePaymentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/creator': {
      id: '/_dashboard/workspace/creator'
      path: '/workspace/creator'
      fullPath: '/workspace/creator'
      preLoaderRoute: typeof DashboardWorkspaceCreatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/business': {
      id: '/_dashboard/workspace/business'
      path: '/workspace/business'
      fullPath: '/workspace/business'
      preLoaderRoute: typeof DashboardWorkspaceBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/account': {
      id: '/_dashboard/workspace/account'
      path: '/workspace/account'
      fullPath: '/workspace/account'
      preLoaderRoute: typeof DashboardWorkspaceAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/management': {
      id: '/_dashboard/docs/management'
      path: '/management'
      fullPath: '/docs/management'
      preLoaderRoute: typeof DashboardDocsManagementRouteImport
      parentRoute: typeof DashboardDocsRoute
    }
    '/_dashboard/docs/legality': {
      id: '/_dashboard/docs/legality'
      path: '/legality'
      fullPath: '/docs/legality'
      preLoaderRoute: typeof DashboardDocsLegalityRouteImport
      parentRoute: typeof DashboardDocsRoute
    }
    '/_dashboard/customer-service/whatsapp': {
      id: '/_dashboard/customer-service/whatsapp'
      path: '/whatsapp'
      fullPath: '/customer-service/whatsapp'
      preLoaderRoute: typeof DashboardCustomerServiceWhatsappRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/website': {
      id: '/_dashboard/customer-service/website'
      path: '/website'
      fullPath: '/customer-service/website'
      preLoaderRoute: typeof DashboardCustomerServiceWebsiteRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/gmail': {
      id: '/_dashboard/customer-service/gmail'
      path: '/gmail'
      fullPath: '/customer-service/gmail'
      preLoaderRoute: typeof DashboardCustomerServiceGmailRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/customer-service/all': {
      id: '/_dashboard/customer-service/all'
      path: '/all'
      fullPath: '/customer-service/all'
      preLoaderRoute: typeof DashboardCustomerServiceAllRouteImport
      parentRoute: typeof DashboardCustomerServiceRoute
    }
    '/_dashboard/workspace/creator/': {
      id: '/_dashboard/workspace/creator/'
      path: '/'
      fullPath: '/workspace/creator/'
      preLoaderRoute: typeof DashboardWorkspaceCreatorIndexRouteImport
      parentRoute: typeof DashboardWorkspaceCreatorRoute
    }
    '/_dashboard/workspace/business/': {
      id: '/_dashboard/workspace/business/'
      path: '/'
      fullPath: '/workspace/business/'
      preLoaderRoute: typeof DashboardWorkspaceBusinessIndexRouteImport
      parentRoute: typeof DashboardWorkspaceBusinessRoute
    }
    '/_dashboard/workspace/discount/voucher': {
      id: '/_dashboard/workspace/discount/voucher'
      path: '/workspace/discount/voucher'
      fullPath: '/workspace/discount/voucher'
      preLoaderRoute: typeof DashboardWorkspaceDiscountVoucherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/discount/referral': {
      id: '/_dashboard/workspace/discount/referral'
      path: '/workspace/discount/referral'
      fullPath: '/workspace/discount/referral'
      preLoaderRoute: typeof DashboardWorkspaceDiscountReferralRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/creator/gallery': {
      id: '/_dashboard/workspace/creator/gallery'
      path: '/gallery'
      fullPath: '/workspace/creator/gallery'
      preLoaderRoute: typeof DashboardWorkspaceCreatorGalleryRouteImport
      parentRoute: typeof DashboardWorkspaceCreatorRoute
    }
    '/_dashboard/workspace/business/token-inject': {
      id: '/_dashboard/workspace/business/token-inject'
      path: '/token-inject'
      fullPath: '/workspace/business/token-inject'
      preLoaderRoute: typeof DashboardWorkspaceBusinessTokenInjectRouteImport
      parentRoute: typeof DashboardWorkspaceBusinessRoute
    }
    '/_dashboard/workspace/ai-model/text': {
      id: '/_dashboard/workspace/ai-model/text'
      path: '/workspace/ai-model/text'
      fullPath: '/workspace/ai-model/text'
      preLoaderRoute: typeof DashboardWorkspaceAiModelTextRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/ai-model/image': {
      id: '/_dashboard/workspace/ai-model/image'
      path: '/workspace/ai-model/image'
      fullPath: '/workspace/ai-model/image'
      preLoaderRoute: typeof DashboardWorkspaceAiModelImageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/workspace/account/user': {
      id: '/_dashboard/workspace/account/user'
      path: '/user'
      fullPath: '/workspace/account/user'
      preLoaderRoute: typeof DashboardWorkspaceAccountUserRouteImport
      parentRoute: typeof DashboardWorkspaceAccountRoute
    }
    '/_dashboard/workspace/account/role': {
      id: '/_dashboard/workspace/account/role'
      path: '/role'
      fullPath: '/workspace/account/role'
      preLoaderRoute: typeof DashboardWorkspaceAccountRoleRouteImport
      parentRoute: typeof DashboardWorkspaceAccountRoute
    }
    '/_dashboard/workspace/account/creator': {
      id: '/_dashboard/workspace/account/creator'
      path: '/creator'
      fullPath: '/workspace/account/creator'
      preLoaderRoute: typeof DashboardWorkspaceAccountCreatorRouteImport
      parentRoute: typeof DashboardWorkspaceAccountRoute
    }
    '/_dashboard/workspace/account/admin': {
      id: '/_dashboard/workspace/account/admin'
      path: '/admin'
      fullPath: '/workspace/account/admin'
      preLoaderRoute: typeof DashboardWorkspaceAccountAdminRouteImport
      parentRoute: typeof DashboardWorkspaceAccountRoute
    }
  }
}

interface DashboardCustomerServiceRouteChildren {
  DashboardCustomerServiceAllRoute: typeof DashboardCustomerServiceAllRoute
  DashboardCustomerServiceGmailRoute: typeof DashboardCustomerServiceGmailRoute
  DashboardCustomerServiceWebsiteRoute: typeof DashboardCustomerServiceWebsiteRoute
  DashboardCustomerServiceWhatsappRoute: typeof DashboardCustomerServiceWhatsappRoute
}

const DashboardCustomerServiceRouteChildren: DashboardCustomerServiceRouteChildren =
  {
    DashboardCustomerServiceAllRoute: DashboardCustomerServiceAllRoute,
    DashboardCustomerServiceGmailRoute: DashboardCustomerServiceGmailRoute,
    DashboardCustomerServiceWebsiteRoute: DashboardCustomerServiceWebsiteRoute,
    DashboardCustomerServiceWhatsappRoute:
      DashboardCustomerServiceWhatsappRoute,
  }

const DashboardCustomerServiceRouteWithChildren =
  DashboardCustomerServiceRoute._addFileChildren(
    DashboardCustomerServiceRouteChildren,
  )

interface DashboardDocsRouteChildren {
  DashboardDocsLegalityRoute: typeof DashboardDocsLegalityRoute
  DashboardDocsManagementRoute: typeof DashboardDocsManagementRoute
}

const DashboardDocsRouteChildren: DashboardDocsRouteChildren = {
  DashboardDocsLegalityRoute: DashboardDocsLegalityRoute,
  DashboardDocsManagementRoute: DashboardDocsManagementRoute,
}

const DashboardDocsRouteWithChildren = DashboardDocsRoute._addFileChildren(
  DashboardDocsRouteChildren,
)

interface DashboardWorkspaceAccountRouteChildren {
  DashboardWorkspaceAccountAdminRoute: typeof DashboardWorkspaceAccountAdminRoute
  DashboardWorkspaceAccountCreatorRoute: typeof DashboardWorkspaceAccountCreatorRoute
  DashboardWorkspaceAccountRoleRoute: typeof DashboardWorkspaceAccountRoleRoute
  DashboardWorkspaceAccountUserRoute: typeof DashboardWorkspaceAccountUserRoute
}

const DashboardWorkspaceAccountRouteChildren: DashboardWorkspaceAccountRouteChildren =
  {
    DashboardWorkspaceAccountAdminRoute: DashboardWorkspaceAccountAdminRoute,
    DashboardWorkspaceAccountCreatorRoute:
      DashboardWorkspaceAccountCreatorRoute,
    DashboardWorkspaceAccountRoleRoute: DashboardWorkspaceAccountRoleRoute,
    DashboardWorkspaceAccountUserRoute: DashboardWorkspaceAccountUserRoute,
  }

const DashboardWorkspaceAccountRouteWithChildren =
  DashboardWorkspaceAccountRoute._addFileChildren(
    DashboardWorkspaceAccountRouteChildren,
  )

interface DashboardWorkspaceBusinessRouteChildren {
  DashboardWorkspaceBusinessTokenInjectRoute: typeof DashboardWorkspaceBusinessTokenInjectRoute
  DashboardWorkspaceBusinessIndexRoute: typeof DashboardWorkspaceBusinessIndexRoute
}

const DashboardWorkspaceBusinessRouteChildren: DashboardWorkspaceBusinessRouteChildren =
  {
    DashboardWorkspaceBusinessTokenInjectRoute:
      DashboardWorkspaceBusinessTokenInjectRoute,
    DashboardWorkspaceBusinessIndexRoute: DashboardWorkspaceBusinessIndexRoute,
  }

const DashboardWorkspaceBusinessRouteWithChildren =
  DashboardWorkspaceBusinessRoute._addFileChildren(
    DashboardWorkspaceBusinessRouteChildren,
  )

interface DashboardWorkspaceCreatorRouteChildren {
  DashboardWorkspaceCreatorGalleryRoute: typeof DashboardWorkspaceCreatorGalleryRoute
  DashboardWorkspaceCreatorIndexRoute: typeof DashboardWorkspaceCreatorIndexRoute
}

const DashboardWorkspaceCreatorRouteChildren: DashboardWorkspaceCreatorRouteChildren =
  {
    DashboardWorkspaceCreatorGalleryRoute:
      DashboardWorkspaceCreatorGalleryRoute,
    DashboardWorkspaceCreatorIndexRoute: DashboardWorkspaceCreatorIndexRoute,
  }

const DashboardWorkspaceCreatorRouteWithChildren =
  DashboardWorkspaceCreatorRoute._addFileChildren(
    DashboardWorkspaceCreatorRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardCrmBlastRoute: typeof DashboardCrmBlastRoute
  DashboardCustomerServiceRoute: typeof DashboardCustomerServiceRouteWithChildren
  DashboardDocsRoute: typeof DashboardDocsRouteWithChildren
  DashboardFinancingRoute: typeof DashboardFinancingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWorkspaceAccountRoute: typeof DashboardWorkspaceAccountRouteWithChildren
  DashboardWorkspaceBusinessRoute: typeof DashboardWorkspaceBusinessRouteWithChildren
  DashboardWorkspaceCreatorRoute: typeof DashboardWorkspaceCreatorRouteWithChildren
  DashboardWorkspacePaymentRoute: typeof DashboardWorkspacePaymentRoute
  DashboardWorkspaceRssRoute: typeof DashboardWorkspaceRssRoute
  DashboardWorkspaceAiModelImageRoute: typeof DashboardWorkspaceAiModelImageRoute
  DashboardWorkspaceAiModelTextRoute: typeof DashboardWorkspaceAiModelTextRoute
  DashboardWorkspaceDiscountReferralRoute: typeof DashboardWorkspaceDiscountReferralRoute
  DashboardWorkspaceDiscountVoucherRoute: typeof DashboardWorkspaceDiscountVoucherRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCrmBlastRoute: DashboardCrmBlastRoute,
  DashboardCustomerServiceRoute: DashboardCustomerServiceRouteWithChildren,
  DashboardDocsRoute: DashboardDocsRouteWithChildren,
  DashboardFinancingRoute: DashboardFinancingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWorkspaceAccountRoute: DashboardWorkspaceAccountRouteWithChildren,
  DashboardWorkspaceBusinessRoute: DashboardWorkspaceBusinessRouteWithChildren,
  DashboardWorkspaceCreatorRoute: DashboardWorkspaceCreatorRouteWithChildren,
  DashboardWorkspacePaymentRoute: DashboardWorkspacePaymentRoute,
  DashboardWorkspaceRssRoute: DashboardWorkspaceRssRoute,
  DashboardWorkspaceAiModelImageRoute: DashboardWorkspaceAiModelImageRoute,
  DashboardWorkspaceAiModelTextRoute: DashboardWorkspaceAiModelTextRoute,
  DashboardWorkspaceDiscountReferralRoute:
    DashboardWorkspaceDiscountReferralRoute,
  DashboardWorkspaceDiscountVoucherRoute:
    DashboardWorkspaceDiscountVoucherRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
