/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWorkspaceRouteImport } from './routes/_admin.workspace'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminRolesRouteImport } from './routes/_admin.roles'
import { Route as AdminLogsRouteImport } from './routes/_admin.logs'
import { Route as AdminFinancingRouteImport } from './routes/_admin.financing'
import { Route as AdminFeedbackRouteImport } from './routes/_admin.feedback'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminComposeRouteImport } from './routes/_admin.compose'
import { Route as AdminBlastRouteImport } from './routes/_admin.blast'
import { Route as AdminNotificationsIdRouteImport } from './routes/_admin.notifications.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspaceRoute = AdminWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancingRoute = AdminFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComposeRoute = AdminComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlastRoute = AdminBlastRouteImport.update({
  id: '/blast',
  path: '/blast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsIdRoute = AdminNotificationsIdRouteImport.update({
  id: '/notifications/$id',
  path: '/notifications/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blast': typeof AdminBlastRoute
  '/compose': typeof AdminComposeRoute
  '/dashboard': typeof AdminDashboardRoute
  '/feedback': typeof AdminFeedbackRoute
  '/financing': typeof AdminFinancingRoute
  '/logs': typeof AdminLogsRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/workspace': typeof AdminWorkspaceRoute
  '/notifications/$id': typeof AdminNotificationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blast': typeof AdminBlastRoute
  '/compose': typeof AdminComposeRoute
  '/dashboard': typeof AdminDashboardRoute
  '/feedback': typeof AdminFeedbackRoute
  '/financing': typeof AdminFinancingRoute
  '/logs': typeof AdminLogsRoute
  '/roles': typeof AdminRolesRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/workspace': typeof AdminWorkspaceRoute
  '/notifications/$id': typeof AdminNotificationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/blast': typeof AdminBlastRoute
  '/_admin/compose': typeof AdminComposeRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/feedback': typeof AdminFeedbackRoute
  '/_admin/financing': typeof AdminFinancingRoute
  '/_admin/logs': typeof AdminLogsRoute
  '/_admin/roles': typeof AdminRolesRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/workspace': typeof AdminWorkspaceRoute
  '/_admin/notifications/$id': typeof AdminNotificationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blast'
    | '/compose'
    | '/dashboard'
    | '/feedback'
    | '/financing'
    | '/logs'
    | '/roles'
    | '/settings'
    | '/users'
    | '/workspace'
    | '/notifications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blast'
    | '/compose'
    | '/dashboard'
    | '/feedback'
    | '/financing'
    | '/logs'
    | '/roles'
    | '/settings'
    | '/users'
    | '/workspace'
    | '/notifications/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/blast'
    | '/_admin/compose'
    | '/_admin/dashboard'
    | '/_admin/feedback'
    | '/_admin/financing'
    | '/_admin/logs'
    | '/_admin/roles'
    | '/_admin/settings'
    | '/_admin/users'
    | '/_admin/workspace'
    | '/_admin/notifications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/workspace': {
      id: '/_admin/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AdminWorkspaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/roles': {
      id: '/_admin/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/logs': {
      id: '/_admin/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/financing': {
      id: '/_admin/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof AdminFinancingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/feedback': {
      id: '/_admin/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/compose': {
      id: '/_admin/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AdminComposeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/blast': {
      id: '/_admin/blast'
      path: '/blast'
      fullPath: '/blast'
      preLoaderRoute: typeof AdminBlastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications/$id': {
      id: '/_admin/notifications/$id'
      path: '/notifications/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof AdminNotificationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlastRoute: typeof AdminBlastRoute
  AdminComposeRoute: typeof AdminComposeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFinancingRoute: typeof AdminFinancingRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWorkspaceRoute: typeof AdminWorkspaceRoute
  AdminNotificationsIdRoute: typeof AdminNotificationsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlastRoute: AdminBlastRoute,
  AdminComposeRoute: AdminComposeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFinancingRoute: AdminFinancingRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWorkspaceRoute: AdminWorkspaceRoute,
  AdminNotificationsIdRoute: AdminNotificationsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
